<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class PhaseLibrariesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $seeds = [
            # hands-on activities (workshop/site visit)
            [
                'phase_detail_id' => 3,
                'nation' => 'all',
                'grade' => '7',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 3,
                'nation' => 'all',
                'grade' => '8',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 3,
                'nation' => 'all',
                'grade' => '9',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 3,
                'nation' => 'US',
                'grade' => '10',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 3,
                'nation' => 'UK',
                'grade' => '10',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 3,
                'nation' => 'US',
                'grade' => '11',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 3,
                'nation' => 'UK',
                'grade' => '11',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 3,
                'nation' => 'US',
                'grade' => '12',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            # talk to professionals
            [
                'phase_detail_id' => 4,
                'nation' => 'all',
                'grade' => '7',
                'quota' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 4,
                'nation' => 'all',
                'grade' => '8',
                'quota' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 4,
                'nation' => 'all',
                'grade' => '9',
                'quota' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 4,
                'nation' => 'US',
                'grade' => '10',
                'quota' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 4,
                'nation' => 'UK',
                'grade' => '10',
                'quota' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 4,
                'nation' => 'Asia',
                'grade' => '10',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 4,
                'nation' => 'US',
                'grade' => '11',
                'quota' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 4,
                'nation' => 'UK',
                'grade' => '11',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 4,
                'nation' => 'Asia',
                'grade' => '11',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            # guided research & reflection
            [
                'phase_detail_id' => 5,
                'nation' => 'all',
                'grade' => '7',
                'quota' => 'Monthly',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 5,
                'nation' => 'all',
                'grade' => '8',
                'quota' => 'Monthly',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 5,
                'nation' => 'all',
                'grade' => '9',
                'quota' => 'Monthly',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 5,
                'nation' => 'all',
                'grade' => '10',
                'quota' => 'Monthly',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 5,
                'nation' => 'all',
                'grade' => '11',
                'quota' => 'Monthly',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 5,
                'nation' => 'all',
                'grade' => '12',
                'quota' => 'Monthly',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            # Competition Guidance
            [
                'phase_detail_id' => 9,
                'nation' => 'all',
                'grade' => '7',
                'quota' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'all',
                'grade' => '8',
                'quota' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'all',
                'grade' => '9',
                'quota' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'US',
                'grade' => '10',
                'quota' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'UK',
                'grade' => '10',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'Asia',
                'grade' => '10',
                'quota' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'US',
                'grade' => '11',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'UK',
                'grade' => '11',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'Asia',
                'grade' => '11',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 9,
                'nation' => 'US',
                'grade' => '12',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            # Personal Project (choose): Research, Internship, Other Projects (podcast, web, campaign)
            [
                'phase_detail_id' => 10,
                'nation' => 'US',
                'grade' => '7',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'UK',
                'grade' => '7',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'Asia',
                'grade' => '7',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'US',
                'grade' => '8',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'UK',
                'grade' => '8',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'Asia',
                'grade' => '8',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'US',
                'grade' => '9',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'UK',
                'grade' => '9',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'Asia',
                'grade' => '9',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'US',
                'grade' => '10',
                'quota' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'UK',
                'grade' => '10',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'US',
                'grade' => '11',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 10,
                'nation' => 'UK',
                'grade' => '11',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            # Community Service Trip (domestic - summer only by batch)
            [
                'phase_detail_id' => 11,
                'nation' => 'US',
                'grade' => '7',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'UK',
                'grade' => '7',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'Asia',
                'grade' => '7',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'US',
                'grade' => '8',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'UK',
                'grade' => '8',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'Asia',
                'grade' => '8',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'US',
                'grade' => '9',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'UK',
                'grade' => '9',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'Asia',
                'grade' => '9',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'phase_detail_id' => 11,
                'nation' => 'US',
                'grade' => '10',
                'quota' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('phase_libraries')->insert($seeds);
    }
}
