<?php

namespace App\Enum;

enum LogModule: string
{   
    case STORE_USER = '[STORE USER]';
    case STORE_ASSET = '[STORE ASSET]';
    case UPDATE_ASSET = '[UPDATE ASSET]';
    case DELETE_ASSET = '[DELETE ASSET]';
    case STORE_ASSET_RETURNED = '[STORE ASSET RETURNED]';
    case DELETE_ASSET_RETURNED = '[DELETE ASSET RETURNED]';
    case STORE_ASSET_USED = '[STORE ASSET USED]';
    case DELETE_ASSET_USED = '[DELETE ASSET USED]';
    case STORE_CURRICULUM = '[STORE CURRICULUM]';
    case UPDATE_CURRICULUM = '[UPDATE CURRICULUM]';
    case DELETE_CURRICULUM = '[DELETE CURRICULUM]';
    case STORE_EDUF_LEAD = '[STORE EDUF LEAD]';
    case UPDATE_EDUF_LEAD = '[UPDATE EDUF LEAD]';
    case DELETE_EDUF_LEAD = '[DELETE EDUF LEAD]';
    case STORE_EDUF_LEAD_SPEAKER = '[STORE EDUF LEAD SPEAKER]';
    case UPDATE_EDUF_LEAD_SPEAKER = '[UPDATE EDUF LEAD SPEAKER]';
    case DELETE_EDUF_LEAD_SPEAKER = '[DELETE EDUF LEAD SPEAKER]';
    case STORE_EDUF_LEAD_REVIEW = '[STORE EDUF LEAD REVIEW]';
    case UPDATE_EDUF_LEAD_REVIEW = '[UPDATE EDUF LEAD REVIEW]';
    case DELETE_EDUF_LEAD_REVIEW = '[DELETE EDUF LEAD REVIEW]';
    case STORE_EVENT = '[STORE EVENT]';
    case UPDATE_EVENT = '[UPDATE EVENT]';
    case DELETE_EVENT = '[DELETE EVENT]';
    case STORE_EVENT_SPEAKER = '[STORE EVENT SPEAKER]';
    case UPDATE_EVENT_SPEAKER = '[UPDATE EVENT SPEAKER]';
    case DELETE_EVENT_SPEAKER = '[DELETE EVENT SPEAKER]';
    case STORE_LEAD = '[STORE LEAD]';
    case UPDATE_LEAD = '[UPDATE LEAD]';
    case DELETE_LEAD = '[DELETE LEAD]';
    case STORE_MAJOR = '[STORE MAJOR]';
    case UPDATE_MAJOR = '[UPDATE MAJOR]';
    case DELETE_MAJOR = '[DELETE MAJOR]';
    case STORE_POSITION = '[STORE POSITION]';
    case UPDATE_POSITION = '[UPDATE POSITION]';
    case DELETE_POSITION = '[DELETE POSITION]';
    case STORE_PROGRAM = '[STORE PROGRAM]';
    case UPDATE_PROGRAM = '[UPDATE PROGRAM]';
    case DELETE_PROGRAM = '[DELETE PROGRAM]';
    case STORE_PURCHASE_REQUEST = '[STORE PURCHASE REQUEST]';
    case UPDATE_PURCHASE_REQUEST = '[UPDATE PURCHASE REQUEST]';
    case DELETE_PURCHASE_REQUEST = '[DELETE PURCHASE REQUEST]';
    case PRINT_PURCHASE_REQUEST = '[PRINT PURCHASE REQUEST]';
    case STORE_PURCHASE_REQUEST_DETAIL = '[STORE PURCHASE REQUEST DETAIL]';
    case UPDATE_PURCHASE_REQUEST_DETAIL = '[UPDATE PURCHASE REQUEST DETAIL]';
    case DELETE_PURCHASE_REQUEST_DETAIL = '[DELETE PURCHASE REQUEST DETAIL]';
    case STORE_SALES_TARGET = '[STORE SALES TARGET]';
    case UPDATE_SALES_TARGET = '[UPDATE SALES TARGET]';
    case DELETE_SALES_TARGET = '[DELETE SALES TARGET]';
    case STORE_SEASONAL_PROGRAM = '[STORE SEASONAL PROGRAM]';
    case UPDATE_SEASONAL_PROGRAM = '[UPDATE SEASONAL PROGRAM]';
    case DELETE_SEASONAL_PROGRAM = '[DELETE SEASONAL PROGRAM]';
    case STORE_SUBJECT = '[STORE SUBJECT]';
    case UPDATE_SUBJECT = '[UPDATE SUBJECT]';
    case DELETE_SUBJECT = '[DELETE SUBJECT]';
    case STORE_TAG = '[STORE TAG]';
    case UPDATE_TAG = '[UPDATE TAG]';
    case DELETE_TAG = '[DELETE TAG]';
    case STORE_VENDOR = '[STORE VENDOR]';
    case UPDATE_VENDOR = '[UPDATE VENDOR]';
    case DELETE_VENDOR = '[DELETE VENDOR]';
}
